import "./globals.scss";
import Header from "@/Components/Header/Header";
import Footer from "@/Components/Footer/Footer";


export const metadata = {
  title: "Amili look shop",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ru">
      <body>
        <Header />
          {children}
        <Footer />
          </body>
    </html>
  );
}
